; asm16 consistency tests

.define TooBigFor8bits 0x1234
.define TooBigFor16bits 0x12345

.org 0xf000

Unop:
    inc     ax,bx               ; try to perform a unary operation on 2 operands

    or      ax                  ; try to perform a binary operation on a single operand
    and     ax
    xor     ax
    mov     ax
    add     ax
    sub     ax
    adc     ax
    sbb     ax

UndefinedId:
    bra     UndefinedLabel
    bcc     UndefinedLabel
    bcs     UndefinedLabel
    bnz     UndefinedLabel
    bz      UndefinedLabel
    bpl     UndefinedLabel
    bmi     UndefinedLabel
    bras    UndefinedLabel
    jmp     UndefinedLabel
    jsr     UndefinedLabel

DuplicateLabel:
    zero    ax
    
DuplicateLabel:
    zero    ax
            
Immed8: 
    inc     ax,#255
    or      ax,#256
    mov     ax,[#1234]
    mov     ax,[#TooBigFor8bits]
    mov     [#0x100],ax
    mov     [#TooBigFor8bits],ax
    mov     ax,[ip+256]
    mov     ax,[ip+TooBigFor8bits]
    mov     [ip+0x100],ax
    mov     [ip+TooBigFor8bits],ax
    and     ax,#TooBigFor8bits
    mov     ax,#TooBigFor8bits
        
Immed16:
    inc     ax,@1234
    zero    ax
    or      ax,@65536
    or      ax,@TooBigFor16bits
    mov     ax,@TooBigFor16bits
    or      ax,TooBigFor16bits
    mov     ax,TooBigFor16bits
    mov     TooBigFor16bits,ax
    mov     ax,@UndefinedLabel

IpRel:
    bra     Baz
    bras    Baz

Filler:
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax

OutOfBranchRange:
    zero    ax
            
