; asm16 consistency tests

.org 0xf000

Unop:
    inc     ax,bx               ; try to perform a unary operation on 2 operands

    or      ax                  ; try to perform a binary operation on a single operand
    and     ax
    xor     ax
    mov     ax
    add     ax
    sub     ax
    adc     ax
    sbb     ax

UndefinedId:
    bra     Foo
    bcc     Foo
    bcs     Foo
    bnz     Foo
    bz      Foo
    bpl     Foo
    bmi     Foo
    bras    Foo
    jmp     Foo
    jsr     Foo

DuplicateLabel:
    zero    ax
    
DuplicateLabel:
    zero    ax
            
Immed8: 
    inc     ax,#255
    or      ax,#256
    mov     ax,[#1234]
    mov     [#0x100],ax
    mov     ax,[ip+256]
    mov     [ip+0x100],ax
        
Immed16:
    inc     ax,@1234
    zero    ax
    or      ax,@65536
    or      ax,[0x10000]
    mov     [0x10000],ax

IpRel:
    bra     Bar
    bras    Bar

Filler:
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax
    zero    ax

Bar:
    zero    ax
            
